apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/conponent: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    #eks.anazonaws.com/role-arn: arn:aws:iam::<accountid>:role/<loadbalancerControllerRoleName>
    eks.anazonaws.com/role-arn: arn:aws:iam::389263978163:role/LoadBalancerControllerRole