apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: eksctl
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<accountId>:role/LoadBalancerControllerRole