apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    #eks.amazonaws.com/role-arn: arn:aws:iam::<accountid>:role/<loadbalancerControllerRoleName>
    eks.amazonaws.com/role-arn: arn:aws:iam::389263978163:role/LoadBalancerControllerRole